/* Generated By:JavaCC: Do not edit this line. SQLparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int WHERE = 8;
  /** RegularExpression Id. */
  int ORDERBY = 9;
  /** RegularExpression Id. */
  int BSIZE = 10;
  /** RegularExpression Id. */
  int RNUM = 11;
  /** RegularExpression Id. */
  int TIMING = 12;
  /** RegularExpression Id. */
  int PRINT = 13;
  /** RegularExpression Id. */
  int WRITE = 14;
  /** RegularExpression Id. */
  int JMODE = 15;
  /** RegularExpression Id. */
  int ID = 16;
  /** RegularExpression Id. */
  int OP = 17;
  /** RegularExpression Id. */
  int VALUE = 18;
  /** RegularExpression Id. */
  int STRING = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"order by\"",
    "\"-bsize\"",
    "\"-rnum\"",
    "\"-timing\"",
    "\"-print\"",
    "\"-write\"",
    "\"-jmode\"",
    "<ID>",
    "<OP>",
    "<VALUE>",
    "<STRING>",
    "\";\"",
    "\"*\"",
    "\",\"",
    "\".\"",
  };

}
