/* Generated By:JavaCC: Do not edit this line. SQLparserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQLparserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AND = 5;
  /** RegularExpression Id. */
  int SELECT = 6;
  /** RegularExpression Id. */
  int FROM = 7;
  /** RegularExpression Id. */
  int WHERE = 8;
  /** RegularExpression Id. */
  int ID = 9;
  /** RegularExpression Id. */
  int OP = 10;
  /** RegularExpression Id. */
  int VALUE = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"AND\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "<ID>",
    "<OP>",
    "<VALUE>",
    "\";\"",
    "\"*\"",
    "\",\"",
    "\".\"",
  };

}
